### PR TITLE
The Next Web responsive design recreation

### PR DESCRIPTION
**Pull request by RodolfoRodriguezMata**
This project recreates The Next Web's layout and how it reacts whenever the width of the view-port is affected. It has three possible set-ups, one above 1024px for computer screens and above, another one from 1023 px down to 768px for handheld screens that allow for several column's worth of content and finally one that goes down from 767px for mobile screens that allow a single stream-lined column of content.

### CODE REVIEW

**Review by imhta — COMMENTED** [review]
# PR Invalid 
### Hello 👋 @mohamedSabry0 @RodolfoRodriguezMata ,  Marking code review request as invalid, because this PR doesn't have a descriptive title and a description and complete the readme.

---
#### Don't forgot to request for another code review
---
**Pon Muthu Selvam**
_If you have any queries, feel free to ping me on slack_

**Comment by Psiale** [comment]
hi! I think you got the wrong github repository, that repository is from
another person.

**Comment by imhta** [comment]
> hi! I think you got the wrong github repository, that repository is from another person.

I am sorry @Psiale 
I copied the invalid template from your pr comment I leaved earlier and mistakenly sumbited review before changing your name tag and then corrected. but it sent mail to you.

**Comment by Psiale** [comment]
yeah no problem, so my pull request stills open to be reviewed?

**Comment by imhta** [comment]
Just request for a another code review @Psiale

**Comment by Psiale** [comment]
I think I can't every time I try to send the form I get the error of "your
already have an open pull request for this project"

**Review by nikasulo — APPROVED** [review]
# Exceptional work @RodolfoRodriguezMata and @mohamedSabry0 :handshake: 
You're both really great developers! Please merge and carry on :rocket:. See you at the top :smile:.

**Pull request merged**
